//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sakshar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sakshar.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string aboutbuttonlabel {
            get {
                return ResourceManager.GetString("aboutbuttonlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakshar makes education more attractive and fun.
        ///It has been developed by PAR Lab (IITD)
        ///In Collaboration with WASEDA University.
        /// </summary>
        public static string aboutmsg {
            get {
                return ResourceManager.GetString("aboutmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancelbuttonlabel {
            get {
                return ResourceManager.GetString("cancelbuttonlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string correctans {
            get {
                return ResourceManager.GetString("correctans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exitbuttonlabel {
            get {
                return ResourceManager.GetString("exitbuttonlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find : .
        /// </summary>
        public static string find {
            get {
                return ResourceManager.GetString("find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  for .
        /// </summary>
        public static string forstring {
            get {
                return ResourceManager.GetString("forstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Finished!!!.
        /// </summary>
        public static string gamefinished {
            get {
                return ResourceManager.GetString("gamefinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Game is going to start....
        /// </summary>
        public static string gameisstartingmsg {
            get {
                return ResourceManager.GetString("gameisstartingmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Touch objects to play the game.
        ///2. Each wrong answer deducts 1 point
        ///3. Right answer adds 4 points.
        ///4. Touch &apos;Exit&apos; button to quit the Game..
        /// </summary>
        public static string howtoplay {
            get {
                return ResourceManager.GetString("howtoplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string howtoplaybuttonlabel {
            get {
                return ResourceManager.GetString("howtoplaybuttonlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong.
        /// </summary>
        public static string incorrectans {
            get {
                return ResourceManager.GetString("incorrectans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAKSHAR welcomes you.
        /// </summary>
        public static string msgwelcome {
            get {
                return ResourceManager.GetString("msgwelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string okbuttonlabel {
            get {
                return ResourceManager.GetString("okbuttonlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points : .
        /// </summary>
        public static string points {
            get {
                return ResourceManager.GetString("points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay.
        /// </summary>
        public static string replaybuttonlabel {
            get {
                return ResourceManager.GetString("replaybuttonlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Seconds.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string startbuttonlabel {
            get {
                return ResourceManager.GetString("startbuttonlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch &apos;Start&apos; to begin the game.
        /// </summary>
        public static string startgamemsg {
            get {
                return ResourceManager.GetString("startgamemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Time : .
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Total Time : .
        /// </summary>
        public static string totaltime {
            get {
                return ResourceManager.GetString("totaltime", resourceCulture);
            }
        }
    }
}
